### ISSUE TITLE
Z axis still not moving

### ISSUE THREAD

**Issue by tbr60702** [Herring-UGAECSE-2920/Class-Instructions#13]
Here is how we currently have the H-Bridge connected to GPIO pins, linear regulator, and Z-axis motor except for Vcc 1&2 and the EN pins. Vcc2 (pin 8) is attached to the linear regulator output instead of 12V. The EN pins & Vcc1 are now connected to the 5V pins on the Raspberry Pi. 

<img width="1264" alt="Screen Shot 2021-02-10 at 4 37 58 PM" src="https://user-images.githubusercontent.com/77293056/107706975-3299de80-6c8f-11eb-920e-f9e86b1f47ba.png">

Our problem is that our z-axis motor is still not spinning when we want it to. It applies tension to the pulley in the downward direction like it is trying to, but it does not actually turn (acts like it is not strong enough).

Here is our script now without the EN pins as GPIOs:

import RPi.GPIO as GPIO
from time import sleep

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(25, GPIO.OUT)
GPIO.setup(4, GPIO.OUT)
GPIO.setup(26, GPIO.OUT)

SIG1A = 26
SIG1B = 4
SIG2A = 27
SIG2B = 25

while True:

            GPIO.output(SIG1A, GPIO.HIGH)
            GPIO.output(SIG1B, GPIO.LOW)
            GPIO.output(SIG2A, GPIO.LOW)
            GPIO.output(SIG2B, GPIO.HIGH)
            sleep(2)
            
            GPIO.output(SIG1A, GPIO.LOW)
            GPIO.output(SIG1B, GPIO.LOW)
            GPIO.output(SIG2A, GPIO.LOW)
            GPIO.output(SIG2B, GPIO.LOW)
            sleep(2)
            
            GPIO.output(SIG1A, GPIO.LOW)
            GPIO.output(SIG1B, GPIO.HIGH)
            GPIO.output(SIG2A, GPIO.HIGH)
            GPIO.output(SIG2B, GPIO.LOW)
            sleep(2)
            
            GPIO.output(SIG1A, GPIO.LOW)
            GPIO.output(SIG1B, GPIO.LOW)
            GPIO.output(SIG2A, GPIO.LOW)
            GPIO.output(SIG2B, GPIO.LOW)
            sleep(2)

At this point we are out of ideas and would appreciate any help.

**Comment by ktkoffroth** [comment]
I believe your stepping sequence is wrong. I would check out [this article](https://en.wikipedia.org/wiki/Stepper_motor) to figure out the correct stepping sequence. I would also suggest severely reducing the wait time in between steps (think milliseconds). Also, make sure your GPIO inputs correspond to the correct coils on the stepper.

Are your EN pins at 5V?
