### ISSUE TITLE
More a concern than an issue

### ISSUE THREAD

**Issue by TJFerg** [Herring-UGAECSE-2920/Class-Instructions#14]
I got the Z motor working for Deliverable 5 just fine. I however was running it just fine without the 12v-5A plugged in. I then plugged it in and ran it again and did not appear to have any change. Is this normal? Was it a fluke? If I kept running it without the regulator plugged in would it have slowly died?

**Comment by ktkoffroth** [comment]
That is definitely not ideal, but if it appears to still be working, you'll be okay. If your H-Bridge fails in the future I would assume this is why.

**Comment by TJFerg** [comment]
NOTED! Thanks
