### ISSUE TITLE
Clarification for Power Supply

### ISSUE THREAD

**Issue by bunnyrun** [Herring-UGAECSE-2920/Class-Instructions#17]
This isn't a technical issue as it is just wanting some clarification.
For the power supply, nothing physical is required to be built, right? Because there's a line in Deliverable 7 that says:

> Design files can include a description (with pictures) of the design, schematics, breadboard pictures, etc.

The "breadboard pictures" is what makes me a bit confused.

Thank you in advance!

**Comment by ktkoffroth** [comment]
That is supposed to convey that you *can* use breadboarding for testing/designing your power supply. It is not a requirement.
