### ISSUE TITLE
Unclear on Manual Calibration 

### ISSUE THREAD

**Issue by ZzzMarky** [Herring-UGAECSE-2920/Class-Instructions#18]
Hi! 
So for the manual calibration section for deliverable 8, are we supposed to write code that allows you to manually change your calibration through some setting on the LCD using the rotary encoders? Or is manual in the sense that you move the plotter physically with your hands to say location x = 15, y = -15, (From the top right) and then have the system calibrate this to be the bounds of the plotter? Meaning the plotter will not plot anything past x = 15 or y = -15?

**Comment by ktkoffroth** [comment]
I can it update to to be more clear, but essentially you are using the etch-a-sketch mode to move the pen to the home position for Math Mode (bottom right of margins) and clicking one of the encoders to set it as the home. This allows you to keep track of the stepper positions and store that location in your code for future use.
