### ISSUE TITLE
Group 9 Spacers - accidently may have turned them in

### ISSUE THREAD

**Issue by ZzzMarky** [Herring-UGAECSE-2920/Class-Instructions#21]
Hi! we may have turned in the spacers that we were supposed to keep from when we first disassembled the x-y plotter. Is there any way we could get those back? Thank you! 
-Group 9

**Comment by ktkoffroth** [comment]
Sure, just come ask before/after class and we can get them for you.

**Comment by ZzzMarky** [comment]
Awesome! will do!
