### ISSUE TITLE
Circle Function - Motor Stepper Size

### ISSUE THREAD

**Issue by catedavis** [Herring-UGAECSE-2920/Class-Instructions#25]
Our horizontal motor step size is 100 steps for 33cm. and our vertical motor step size is 100 steps for 16cm. This causes problems when trying to calculate the decision parameters for the midpoint and Bresenham circle algorithm. I have tried to slip the radius into x and y legs, but that logically does not make sense. I talked to another group and their vertical and horizontal step sizes are the same. How do we implement the circle with different x and y step sizes?

**Comment by jealford** [comment]
You shouldn't have such a large difference in the x and y. I would check to make sure you're using the same step type for both.

**Comment by ktkoffroth** [comment]
In addition to Jake's comment, I know that the motors are rated as 200 steps/revolution, meaning that you would need to find a correlation between this smallest step size and distance traveled. The step sizes for both motors should be the same in this regard.
