### ISSUE TITLE
Arc Command Validation

### ISSUE THREAD

**Issue by aarcowedu** [Herring-UGAECSE-2920/Class-Instructions#30]
![image](https://user-images.githubusercontent.com/47263726/115051144-8224a280-9eaa-11eb-9959-de85f54fa0a7.png)
![image](https://user-images.githubusercontent.com/47263726/115051132-7e911b80-9eaa-11eb-84c8-66f85f4bd5fa.png)
![image](https://user-images.githubusercontent.com/47263726/115051109-75a04a00-9eaa-11eb-96a6-7416d941f7d9.png)
We ran into an issue with the second test file on both Monday's and Friday's gcode tests.
While most of our arcs draw correctly, some of the arcs seem to be invalid, as shown above in a plot of an example in the test.

The gcode req's specify that we should validate arcs before attempting to draw them (referring to G02 and G03).
What should our program do when an invalid arc command is given? We've come up with a few possible solutions, but we're not sure which one to pick.

1. Stop drawing and display a bad gcode error
2. draw a straight line instead of an arc
3. skip to the next command and draw from its current position, leading the next line to also be wrong
4. use the arc endpoint as part of the next command, leading the next line to be right

We are heavily leaning towards solution 1 as it would make the most sense, but we can't find a specification in the req's.

**Comment by ktkoffroth** [comment]
Hi @aarcowedu  there should not be any invalid arc commands in those files, I'll look into it, thanks

**Comment by ktkoffroth** [comment]
@aarcowedu It appeared to be an issue with the arc offsets, changed it from 10 to 5. You can re-download the files and we'll make an announcement in class today.
