### ISSUE TITLE
Twitching Z-Motor

### ISSUE THREAD

**Issue by ajb82204** [Herring-UGAECSE-2920/Class-Instructions#31]
Our Z-motor randomly starts twitching during operation and we lose control of it. It will start doing it even when we aren't running code.

**Comment by ktkoffroth** [comment]
@ajb82204 Is the motor getting particularly hot during operation?

**Comment by ajb82204** [comment]
It is warm. Not hot. The twitching starts off slow and then gets faster.

**Comment by ktkoffroth** [comment]
@ajb82204 can you send me the exact wiring setup between your Pi, Power Circuitry (Buck Converter), and H-Bridge? And which file controls your Z-Stepper motor in your Repo?

**Comment by ajb82204** [comment]
Are you in driftmier? It would be easier to show you.

**Comment by ktkoffroth** [comment]
@ajb82204 I am, trying to fix some issues with the G-Code files, which room are y'all in?
