### ISSUE TITLE
LCD Issue

### ISSUE THREAD

**Issue by UaNotJosh** [Herring-UGAECSE-2920/Class-Instructions#6]
Hi everyone, 
Group 3 had some issues with our LCD screen and while we do not have all the details we might need, I havemost of what we think was going on.
We were trying to run the "Button.py" test code that is part of the download from the LCD documentation that everyone should have used
It was in its own "Button" directory within a few others, I can push these into GitHub tomorrow to make the understanding easier
There were no errors from the program itself, only errors in how it operated on the screen, or moreso didn't operate in this case
I do not have a picture of the setup, simply because my group member has the LCD screen while I have the pi itself but again, I can post a picture of this tomorrow for further clarity. However, we just connected the LCD screen directly onto the pins of the pi in a vertical fashion
Thanks in advance for any help!

**Comment by ktkoffroth** [comment]
Hey @UaNotJosh , did you guys make sure to connect the button GPIO pins (on the hat, a six pin set) to the GPIO pins (on the pi, a 40 pin connector) specified in the sample code?
